# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-northeast-1"
    bucket         = "iu-ai-4-cyber-team-3-tf-remote-state"
  }
}
